### ISSUE TITLE
Unable to build forge.min.js

### ISSUE THREAD

**Issue by MithunChopda** [whiteout-io/tcp-socket#15]
I am unable to build the forge.min.js. The commands succeed by do not yield anything.
Can you please provide a download link for forge.min.js  OR
can I use the forge.js found under node_modules/js folder?

Thanks in advance.

**Comment by felixhammerl** [comment]
https://github.com/digitalbazaar/forge#building-a-browser-bundle

npm test builds this. forge is then copied appriopriately for the tests. as for your app, you'll have to manage the dependencies yourself. depending on what you wanna do you might not need it at all
